name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14.15.0']
        flavor: ['', '-intl', '-native', '-native-intl']

    steps:
    - uses: actions/checkout@v2
    - name: Prepare build settings for intl
      id: prep-intl
      if: matrix.flavor == '-intl' || matrix.flavor == '-native-intl'
      run: echo '::set-output name=INTL::true'
    - name: Prepare build settings for native
      id: prep-native
      if: matrix.flavor == '-native' || matrix.flavor == '-native-intl'
      run: echo '::set-output name=NATIVE::true'
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jcrugzz/s6-node-alpine:${{ matrix.node_version }}${{ matrix.flavor }} --build-arg INTL=${{ steps.prep-intl.outputs.INTL }} --build-arg NATIVE=${{ steps.prep-native.outputs.NATIVE }}
    - name: Docker Login
      uses: docker/login-action@v1.6.0
      with:
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.docker_token }}
    - name: Push the Docker image
      run: docker push jcrugzz/s6-node-alpine:${{ matrix.node-version }}${{ matrix.flavor }}
